/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4_colegio;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author gonza
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public static HashSet<Alumno> alumnos = new HashSet<>();
    public static HashSet<Materia> materias = new HashSet<>();

    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        this.alumnos = alumnos;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktoopPane = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        mnuAlumno = new javax.swing.JMenu();
        mnuAltaAlumno = new javax.swing.JMenuItem();
        mnuMateria = new javax.swing.JMenu();
        mnuAltaMateria = new javax.swing.JMenuItem();
        mnuRegistro = new javax.swing.JMenu();
        mnuInscripcion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JDesktoopPaneLayout = new javax.swing.GroupLayout(JDesktoopPane);
        JDesktoopPane.setLayout(JDesktoopPaneLayout);
        JDesktoopPaneLayout.setHorizontalGroup(
            JDesktoopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        JDesktoopPaneLayout.setVerticalGroup(
            JDesktoopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        getContentPane().add(JDesktoopPane, java.awt.BorderLayout.CENTER);

        mnuAlumno.setText("Alumno");

        mnuAltaAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAltaAlumno.setText("Alta de alumnos");
        mnuAltaAlumno.addActionListener(this::mnuAltaAlumnoActionPerformed);
        mnuAlumno.add(mnuAltaAlumno);

        menu.add(mnuAlumno);

        mnuMateria.setText("Materia");

        mnuAltaMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAltaMateria.setText("Alta de Materias");
        mnuAltaMateria.addActionListener(this::mnuAltaMateriaActionPerformed);
        mnuMateria.add(mnuAltaMateria);

        menu.add(mnuMateria);

        mnuRegistro.setText("Registro");

        mnuInscripcion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuInscripcion.setText("Formulario de inscripción");
        mnuInscripcion.addActionListener(this::mnuInscripcionActionPerformed);
        mnuRegistro.add(mnuInscripcion);

        menu.add(mnuRegistro);

        mnuSalir.setText("Salir");

        mnuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemSalir.setText("Salir");
        mnuItemSalir.addActionListener(this::mnuItemSalirActionPerformed);
        mnuSalir.add(mnuItemSalir);

        menu.add(mnuSalir);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAltaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaAlumnoActionPerformed
        VistaAlumnos vista = new VistaAlumnos(alumnos);
        JDesktoopPane.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_mnuAltaAlumnoActionPerformed

    private void mnuAltaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAltaMateriaActionPerformed
        VistaMaterias vista = new VistaMaterias(materias);
        JDesktoopPane.add(vista);
        vista.setVisible(true);
    }//GEN-LAST:event_mnuAltaMateriaActionPerformed

    private void mnuInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInscripcionActionPerformed
           VistaInscripcion vista = new VistaInscripcion(alumnos, materias);
    JDesktoopPane.add(vista);
    vista.setVisible(true);
    }//GEN-LAST:event_mnuInscripcionActionPerformed

    private void mnuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       // Carga de datos de prueba, para no tener que tipearlos en la GUI cada vez
    Materia web2 = new Materia(1, "WEB 2", 2);
    Materia mat1 = new Materia(2, "Matemáticas 1", 1);
    Materia lab1 = new Materia(3, "Laboratorio 1", 1);
    materias.add(web2);
    materias.add(mat1);
    materias.add(lab1);
    Alumno a1 = new Alumno(1001, "Lopez", "Martin");
    Alumno a2 = new Alumno(1002, "Martinez", "Brenda");
    alumnos.add(a1);
    alumnos.add(a2);

    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktoopPane;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem mnuAltaAlumno;
    private javax.swing.JMenuItem mnuAltaMateria;
    private javax.swing.JMenu mnuAlumno;
    private javax.swing.JMenuItem mnuInscripcion;
    private javax.swing.JMenuItem mnuItemSalir;
    private javax.swing.JMenu mnuMateria;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
